ticker_map = {
    # Ticker symbols (lowercase)
    "aapl": "AAPL",
    "abnb": "ABNB",
    "adbe": "ADBE",
    "adi": "ADI",
    "adp": "ADP",
    "adsk": "ADSK",
    "aep": "AEP",
    "alny": "ALNY",
    "amat": "AMAT",
    "amd": "AMD",
    "amgn": "AMGN",
    "amzn": "AMZN",
    "app": "APP",
    "arm": "ARM",
    "asml": "ASML",
    "avgo": "AVGO",
    "axon": "AXON",
    "azn": "AZN",
    "bkng": "BKNG",
    "bkr": "BKR",
    "ccep": "CCEP",
    "cdns": "CDNS",
    "ceg": "CEG",
    "chtr": "CHTR",
    "cmcsa": "CMCSA",
    "cme": "CME",
    "coin": "COIN",
    "cost": "COST",
    "cprt": "CPRT",
    "crwd": "CRWD",
    "crwv": "CRWV",
    "csco": "CSCO",
    "csx": "CSX",
    "ctas": "CTAS",
    "ctsh": "CTSH",
    "dash": "DASH",
    "ddog": "DDOG",
    "ea": "EA",
    "eqix": "EQIX",
    "exc": "EXC",
    "fang": "FANG",
    "fast": "FAST",
    "ftnt": "FTNT",
    "gild": "GILD",
    "googl": "GOOGL",
    "hon": "HON",
    "hood": "HOOD",
    "ibkr": "IBKR",
    "idxx": "IDXX",
    "intc": "INTC",
    "intu": "INTU",
    "isrg": "ISRG",
    "jd": "JD",
    "kdp": "KDP",
    "klac": "KLAC",
    "kmb": "KMB",
    "lin": "LIN",
    "lrcx": "LRCX",
    "mar": "MAR",
    "mdlz": "MDLZ",
    "meli": "MELI",
    "meta": "META",
    "mnst": "MNST",
    "mrvl": "MRVL",
    "msft": "MSFT",
    "mstr": "MSTR",
    "mu": "MU",
    "ndaq": "NDAQ",
    "nflx": "NFLX",
    "ntes": "NTES",
    "nvda": "NVDA",
    "nxpi": "NXPI",
    "orly": "ORLY",
    "panw": "PANW",
    "payx": "PAYX",
    "pcar": "PCAR",
    "pdd": "PDD",
    "pep": "PEP",
    "pltr": "PLTR",
    "pypl": "PYPL",
    "qcom": "QCOM",
    "regn": "REGN",
    "rop": "ROP",
    "rost": "ROST",
    "sbux": "SBUX",
    "shop": "SHOP",
    "snps": "SNPS",
    "sny": "SNY",
    "tcom": "TCOM",
    "team": "TEAM",
    "tmus": "TMUS",
    "tri": "TRI",
    "tsla": "TSLA",
    "ttwo": "TTWO",
    "txn": "TXN",
    "vrsk": "VRSK",
    "vrtx": "VRTX",
    "wday": "WDAY",
    "xel": "XEL",
    "zs": "ZS",
    
    # Company names (lowercase)
    "apple": "AAPL",
    "airbnb": "ABNB",
    "adobe": "ADBE",
    "analog devices": "ADI",
    "automatic data processing": "ADP",
    "autodesk": "ADSK",
    "american electric power": "AEP",
    "alnylam": "ALNY",
    "applied materials": "AMAT",
    "advanced micro devices": "AMD",
    "amgen": "AMGN",
    "amazon": "AMZN",
    "arm holdings": "ARM",
    "asml": "ASML",
    "broadcom": "AVGO",
    "axon enterprise": "AXON",
    "astrazeneca": "AZN",
    "booking holdings": "BKNG",
    "baker hughes": "BKR",
    "coca cola europacific": "CCEP",
    "cadence design": "CDNS",
    "constellation energy": "CEG",
    "charter communications": "CHTR",
    "comcast": "CMCSA",
    "cme group": "CME",
    "coinbase": "COIN",
    "costco": "COST",
    "copart": "CPRT",
    "crowdstrike": "CRWD",
    "cisco": "CSCO",
    "csx": "CSX",
    "cintas": "CTAS",
    "cognizant": "CTSH",
    "doordash": "DASH",
    "datadog": "DDOG",
    "electronic arts": "EA",
    "equinix": "EQIX",
    "exelon": "EXC",
    "fastenal": "FAST",
    "fortinet": "FTNT",
    "gilead sciences": "GILD",
    "alphabet": "GOOGL",
    "google": "GOOGL",
    "honeywell": "HON",
    "robinhood": "HOOD",
    "interactive brokers": "IBKR",
    "idexx": "IDXX",
    "intel": "INTC",
    "intuit": "INTU",
    "intuitive surgical": "ISRG",
    "jd.com": "JD",
    "keurig dr pepper": "KDP",
    "kla": "KLAC",
    "kimberly clark": "KMB",
    "linde": "LIN",
    "lam research": "LRCX",
    "marriott": "MAR",
    "mondelez": "MDLZ",
    "mercadolibre": "MELI",
    "meta platforms": "META",
    "facebook": "META",
    "monster beverage": "MNST",
    "marvell": "MRVL",
    "microsoft": "MSFT",
    "microstrategy": "MSTR",
    "micron": "MU",
    "nasdaq": "NDAQ",
    "netflix": "NFLX",
    "netease": "NTES",
    "nvidia": "NVDA",
    "nxp semiconductors": "NXPI",
    "o'reilly automotive": "ORLY",
    "palo alto networks": "PANW",
    "paychex": "PAYX",
    "paccar": "PCAR",
    "pdd holdings": "PDD",
    "pepsico": "PEP",
    "pepsi": "PEP",
    "palantir": "PLTR",
    "paypal": "PYPL",
    "qualcomm": "QCOM",
    "regeneron": "REGN",
    "roper": "ROP",
    "ross stores": "ROST",
    "starbucks": "SBUX",
    "shopify": "SHOP",
    "synopsys": "SNPS",
    "sanofi": "SNY",
    "trip.com": "TCOM",
    "atlassian": "TEAM",
    "t-mobile": "TMUS",
    "thomson reuters": "TRI",
    "tesla": "TSLA",
    "take-two": "TTWO",
    "texas instruments": "TXN",
    "verisk": "VRSK",
    "vertex": "VRTX",
    "workday": "WDAY",
    "xcel energy": "XEL",
    "zscaler": "ZS",
}
